import React from 'react';

const DisclaimerContent = () => {
    return (
        <div className="max-w-4xl mx-auto p-6">
            <h2 className="font-bold mb-4 text-3xl text-black">Terms of Service</h2>
            <p className="mb-8 text-black">Please read these terms carefully and keep a copy of them for your reference. Please also note that there may be specific terms or conditions applicable to you as a user in a given jurisdiction, as detailed below.</p>
            <p className="mb-4 text-black">Please refer to our Privacy Policy, available at link, for information about how we collect, use, share and otherwise process information about you.</p>
            <h3 className="font-bold mb-4 text-black">AGREEMENT TO TERMS</h3>
            <p className="mb-4 text-black">This End User License Agreement and Terms of Service (“EULA” or “Terms”) is a binding contract between you, an individual user or site visitor, whether personally or on behalf of an entity (“user,” “you,” “your”) and OptimusZ7 Inc (the “Inc,” “we,” “us” or “our”) concerning use of the Inc’s services (the “Service”), including the www.optimusz7.com website as well as any other media form, media channel, or mobile website related, linked, or otherwise connected thereto (collectively, the “Site”). Currently, the Inc maintains and operates www.optimusz7.com as a portal for news, information, and updates about the OptimusZ7 protocol or blockchain (the “OptimusZ7 Network”) and the OptimusZ7 ecosystem. For the avoidance of doubt, the Inc does not control the OptimusZ7 Network and cannot control activity and data on the OptimusZ7 Network, the activities of persons who develop and use applications on the Network, the validation of transactions on the OptimusZ7 Network, or use of the OptimusZ7 Network. The OptimusZ7 Network is an open-source protocol that is maintained and processed by OptimusZ7 Network validators across the globe.</p>
            <p className="mb-4 text-black">BY ACCESSING OR USING THE SERVICE, YOU AGREE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THE EULA. IF YOU DO NOT AGREE, PLEASE DO NOT USE THE SERVICE OR SITE.</p>
            <p className="mb-4 text-black">Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to this EULA at any time and for any reason. We will alert you about any changes by updating the “Last updated” date of the EULA, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review the EULA to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised EULA by your continued use of the Service after the date such revised EULA is posted.</p>
            <p className="mb-4 text-black">The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.</p>
            <p className="mb-8 text-black">The Service is intended for users who are at least 18 years old. You agree that by using the Site and the Service you are at least 18 years of age, or accessing the Service under the supervision of a parent or guardian, and you are legally able to enter into a contract. If you are a parent or legal guardian of a user under the age of 18 (or the age of legal majority), you agree to be fully responsible for the acts or omissions of such user in relation to the Service. If you use the Service on behalf of another person or entity, (a) all references to “you” throughout the EULA will include that person or entity, (b) you represent that you are authorized to accept these Terms on that person’s or entity’s behalf, and (c) in the event you or the person or entity violates these Terms, the person or entity agrees to be responsible to us.</p>
            <p className="mb-4 text-black"><strong className="text-red-600">PLEASE NOTE:</strong> THE “DISPUTE RESOLUTION” SECTION OF THIS EULA CONTAINS AN ARBITRATION CLAUSE THAT REQUIRES DISPUTES TO BE ARBITRATED ON AN INDIVIDUAL BASIS, AND PROHIBITS CLASS ACTION CLAIMS. IT AFFECTS HOW DISPUTES BETWEEN YOU AND THE INC ARE RESOLVED. BY ACCEPTING THIS EULA, YOU AGREE TO BE BOUND BY THIS ARBITRATION PROVISION. PLEASE READ IT CAREFULLY.</p>
            <h3 className="font-bold mb-4 text-black">SCOPE OF LICENSE TO USERS</h3>
            <p className="mb-4 text-black">The Service is licensed, not sold, to you for use only under the terms of the EULA, subject to your complete and ongoing compliance with the terms and conditions of the EULA. The Inc hereby grants you a personal, limited, revocable, non-transferable license to access and use the Service solely for your own use.</p>
            <p className="mb-4 text-black">You may not modify, alter, reproduce, or distribute the Service. You may not directly rent, lease, lend, sell, redistribute or sublicense the Service. You may not copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of any portion of the Service, any updates, or any part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law), nor attempt to disable or circumvent any security or other technological measure designed to protect the Service or any content available through the Service. If you breach these license restrictions, or otherwise exceed the scope of the licenses granted in the EULA, then you may be subject to prosecution and damages, as well as liability for infringement of intellectual property rights, and denial of access to the Service.</p>
            <p className="mb-4 text-black">WITHOUT LIMITING ANY OTHER PROVISION OF THIS EULA, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICE (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THIS EULA OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SITE AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION. If we terminate or suspend your access to the Site for any reason, you are prohibited from attempting to access the Site under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party. In addition to terminating or suspending your access, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.</p>
            <h2 className="font-bold mb-4 text-black">Prohibited Activities</h2>
            <p className="mb-8 text-black">You may not access or use the Service for any purpose other than that for which we make the Service available. The Service may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us. As a user of the Service, you agree not to:</p>
            <ul className="list-disc mb-8 text-black">
                <li className="mb-4">Systematically retrieve data or other content from the Service to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
                <li className="mb-4">Make any unauthorized use of the Service, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.</li>
                <li className="mb-4">Circumvent, disable, or otherwise interfere with security-related features of the Service, including features that prevent or restrict the use or copying of any content or enforce limitations on the use of the Service or the content contained therein.</li>
                <li className="mb-4">Engage in unauthorized framing of or linking to the Service.</li>
                <li className="mb-4">Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
                <li className="mb-4">Use any information obtained from the Service in order to harass, abuse, or harm another person.</li>
                <li className="mb-4">Use the Service in a manner inconsistent with any applicable laws or regulations.</li>
                <li className="mb-4">Disrupt, interfere with, or otherwise cause harm to the Service, including by introducing any viruses, worms, defects, Trojan horses, or other malicious code into the Service.</li>
            </ul>
            <h2 className="font-bold mb-4 text-black">Changes to the Terms</h2>
            <p className="mb-4 text-black">We may revise these Terms from time to time in our sole discretion. All changes are effective immediately when we post them and apply to all access to and use of the Service thereafter. Your continued use of the Service following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page regularly so you are aware of any changes, as they are binding on you.</p>
            <h2 className="font-bold mb-4 text-black">Contact Us</h2>
            <p className="mb-4 text-black">If you have any questions about these Terms, please contact us at: support@optimusz7.com</p>
        </div>
    );
};

export default DisclaimerContent;
